apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-message-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sameershah21/argoevents # Replace with your Git repository URL
    path: flask-app.yaml # Replace with the path to the 'flask-app.yaml' file in your repository
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
